### ISSUE TITLE
doesn't add up

### ISSUE THREAD

**Issue by jonattot** [deltapi/abc-feedback#13] opened 2021-10-10 00:31 UTC
I was given 1,148,622,263,469,785,000 + 3,928,797,478,390,152,481 = 5,077,419,741,859,937,000
but 1,148,622,263,469,785,000 + 3,928,797,478,390,152,481 =5,077,419,741,859,937,481

still a counter-example,  the radical is 82,894,724,034,279,690 < c

**Comment by KaustubhRakhade** [comment] 2021-10-10 03:51
Duplicate of #6

**Closed as completed** 2021-10-10 14:34 UTC
Labels: duplicate
