### ISSUE TITLE
Addition result is false

### ISSUE THREAD

**Issue by Overscore** [deltapi/abc-feedback#22] opened 2021-10-15 09:19 UTC
Here one of my results:

We found 1 triples for 1817 ≦ rad(a) < 1818, 2211 ≦ rad(b) < 2212! Here you go:
21944570769 + 802550538496000000 = 802550560440570800,
q=1.0470343874138623

**Comment by KaustubhRakhade** [comment] 2021-10-15 09:26
Duplicate of #6

**Closed as completed** 2021-10-17 09:52 UTC
